kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: chluehr/phpab
    tags:
      - latest
      - '1.29.2'
      - '1.29'
      - '1'
    username: 
        from_secret: docker_username
    password: 
        from_secret: docker_password


